# Generated by Django 4.2.20 on 2025-04-03 06:47

from django.db import migrations, models
import freecourseresources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(default=freecourseresources.models.generate_random_rating)),
                ('course_link', models.URLField(unique=True)),
                ('image_url', models.URLField(default='https://example.com/default-course-image.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Free Course Resource',
                'verbose_name_plural': 'Free Course Resources',
                'db_table': 'free_course_resources',
            },
        ),
    ]
